### ISSUE TITLE
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'

### ISSUE THREAD

**Issue by shiyi-z** [HumamAlwassel/DETAD#11]
it occurs some errors when i use the thumos samples you have provided.

＇python false_negative_analysis.py --ground_truth_filename ../data/thumos14_test_extra_characteristics.json --subset testing --prediction_filename ../data/CMS-RC3D_predictions_on_thumos14_testing_subset.json --output_folder ../output/thumos14＇

![image](https://github.com/HumamAlwassel/DETAD/assets/79558156/7201c117-7363-4c50-b9dc-3df2cc801dc8)

can you help me to sovle this problem? thank you very much!

**Comment by thanhhff** [comment]
Hi @shiyi-z,
I also got this problem when trying to analyze the THUMOS14 dataset.
This problem comes from when loading `characteristic_name`, the characteristics of THUMOS14 only have "Converage", "Length", and "# Instances". 
So, to fix this problem, you need to ignore `null` characteristics in the ground truth file.

When running the bash, you only need to add `--is_thumos14` for the THUMOS14 dataset.
