### ISSUE TITLE
Missing annotations on context-size, context-distances and agreement on ActivityNet

### ISSUE THREAD

**Issue by zijunwei** [HumamAlwassel/DETAD#2]
Any plans to release these annotations?

**Comment by HumamAlwassel** [comment]
Hi Zijun,

Thank you for your interest in our DETAD work. Due to the expensive cost, we only collected such annotations for the testing subset of ActivtyNet. Since the testing subset is withheld for the annual ActivityNet Challenge in CVPR, we cannot release these annotations. 
However, we incorporated the DETAD analysis as part of [the ActivityNet evaluation server](http://activity-net.org/challenges/2018/evaluation.html) for the temporal localization task. Please submit your results through the server and you will get back the DETAD analysis in a PDF format.

Cheers,

**Comment by zijunwei** [comment]
Thanks for the clarification!
